version: '3'
services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  monitor-db-setup:
    image: projecteka/monitor-db-initializer
    container_name: monitor-db-setup
    environment:
      - 'JAVA_TOOL_OPTIONS=-Djdbc.url=jdbc:postgresql://postgres:5432/monitor -Djdbc.username=postgres -Djdbc.password=password'
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local