server:
  port: 8004
monitor:
  db:
    host: localhost
    port: 5432
    schema: monitor
    user: postgres
    password: password
    poolSize: 5
  gatewayservice:
    baseUrl: http://localhost:8000/v0.5
  scheduler:
    initialDelay: 10000
    interval: 60000
