server:
  port: 8004
monitor:
  db:
    host: localhost
    port: 5432
    schema: monitor
    user: postgres
    password: password
    poolSize: 5
  gatewayservice:
    baseUrl: https://preprod.ndhm.gov.in/gateway/v0.5
